export interface Product {
    id: string;
    name: string;
    description: string;
    price: number;
    originalPrice: number | null;
    image: string;
    category: "clásicas" | "premium" | "especiales";
    tag: string | null;
    rating: number;
    reviews: number;
    calories: number;
    weight: string;
    ingredients: string[];
    isNew: boolean;
    isBestSeller: boolean;
    isVegan: boolean;
    isFeatured: boolean;
    texture: string;
    intensity: string;
    pairings: string[];
    accentClass: string;
  }
  
  export const PRODUCTS: Product[] = [
    {
      id: "chocochip-deluxe",
      name: "NY Chocochip Deluxe",
      description: "La clásica reinventada. Chips de chocolate belga sobre masa de mantequilla tostada. Irresistible.",
      price: 5.99,
      originalPrice: null,
      image: "/images/products/slider1.png",
      category: "clásicas",
      tag: "best seller",
      rating: 4.9,
      reviews: 312,
      calories: 250,
      weight: "90g",
      ingredients: ["Choco Belga", "Mantequilla", "Vainilla"],
      isNew: false,
      isBestSeller: true,
      isVegan: false,
      isFeatured: true,
      texture: "suave",
      intensity: "medio",
      pairings: ["Leche", "Café"],
      accentClass: "from-chocolate-600 to-chocolate-800",
    },
    {
      id: "triple-chocolate",
      name: "Triple Chocolate Overdose",
      description: "Cacao en la masa, chips de chocolate oscuro y cobertura de ganache. Para los valientes.",
      price: 9.49,
      originalPrice: null,
      image: "/images/products/slider2.png",
      category: "premium",
      tag: "más vendido",
      rating: 5.0,
      reviews: 198,
      calories: 320,
      weight: "100g",
      ingredients: ["Cacao 85%", "Ganache", "Choco Blanco"],
      isNew: false,
      isBestSeller: true,
      isVegan: false,
      isFeatured: true,
      texture: "suave",
      intensity: "intenso",
      pairings: ["Café", "Vino Tinto"],
      accentClass: "from-chocolate-700 to-chocolate-900",
    },
    {
      id: "caramel-sea-salt",
      name: "Caramel Sea Salt Bliss",
      description: "Una explosión salada-dulce inigualable.",
      price: 8.49,
      originalPrice: null,
      image: "/images/products/slider3.png",
      category: "premium",
      tag: "limitado",
      rating: 4.9,
      reviews: 112,
      calories: 210,
      weight: "80g",
      ingredients: ["Caramelo", "Sal Marina", "Choco Oscuro"],
      isNew: false,
      isBestSeller: true,
      isVegan: false,
      isFeatured: false,
      texture: "suave",
      intensity: "medio",
      pairings: ["Café", "Whisky"],
      accentClass: "from-cookie-400 to-cookie-700",
    },
    {
      id: "red-velvet",
      name: "NY Lemon Pie",
      description: "Galleta cítrica con crema de queso y chispas de chocolate blanco. Fresca, aterciopelada y perfecta.",
      price: 7.99,
      originalPrice: null,
      image: "/images/products/slider4.png",
      category: "premium",
      tag: "nuevo",
      rating: 4.8,
      reviews: 96,
      calories: 195,
      weight: "75g",
      ingredients: ["Limón", "Crema de Queso", "Vainilla"],
      isNew: true,
      isBestSeller: false,
      isVegan: false,
      isFeatured: false,
      texture: "suave",
      intensity: "suave",
      pairings: ["Té", "Champán"],
      accentClass: "from-cookie-500 to-chocolate-500",
    },
    {
      id: "oreo-crunch",
      name: "Oreo Crunch Supreme",
      description: "Galleta doble con crema de Oreo, trozos crujientes y chocolate cremoso.",
      price: 6.99,
      originalPrice: null,
      image: "/images/products/slider5.png",
      category: "clásicas",
      tag: "fan favorite",
      rating: 4.8,
      reviews: 203,
      calories: 260,
      weight: "95g",
      ingredients: ["Oreo", "Crema", "Choco Leche"],
      isNew: false,
      isBestSeller: true,
      isVegan: false,
      isFeatured: false,
      texture: "crujiente",
      intensity: "medio",
      pairings: ["Leche", "Café"],
      accentClass: "from-chocolate-600 to-chocolate-800",
    },
    {
      id: "matcha-green",
      name: "NY Chocolor",
      description: "Matcha japonés premium con chips de chocolate blanco. Un contraste que despierta todos los sentidos.",
      price: 7.99,
      originalPrice: null,
      image: "/images/products/slider6.png",
      category: "especiales",
      tag: null,
      rating: 4.7,
      reviews: 74,
      calories: 180,
      weight: "70g",
      ingredients: ["Matcha", "Choco Blanco", "Almendra"],
      isNew: false,
      isBestSeller: false,
      isVegan: true,
      isFeatured: false,
      texture: "suave",
      intensity: "suave",
      pairings: ["Té verde", "Leche de almendras"],
      accentClass: "from-cookie-600 to-cookie-900",
    },
    {
      id: "brown-butter-pecan",
      name: "Brown Butter Pecan",
      description: "Mantequilla dorada a fuego lento, nueces pecanas tostadas y una pizca de canela.",
      price: 8.99,
      originalPrice: 10.99,
      image: "/images/products/slider7.png",
      category: "premium",
      tag: "nuevo",
      rating: 4.9,
      reviews: 87,
      calories: 240,
      weight: "90g",
      ingredients: ["Mantequilla Dorada", "Pecan", "Canela"],
      isNew: true,
      isBestSeller: true,
      isVegan: false,
      isFeatured: false,
      texture: "crujiente",
      intensity: "medio",
      pairings: ["Café", "Sidra"],
      accentClass: "from-amber-700 to-cookie-800",
    },
    {
      id: "pistachio-rose",
      name: "Pistachio Rose Dream",
      description: "Pistachos iraníes molidos sobre masa de agua de rosas y chocolate blanco. Exótico y delicado.",
      price: 9.99,
      originalPrice: 12.49,
      image: "/images/products/slider8.png",
      category: "especiales",
      tag: "nuevo",
      rating: 4.8,
      reviews: 53,
      calories: 200,
      weight: "75g",
      ingredients: ["Pistacho", "Agua de Rosas", "Choco Blanco"],
      isNew: true,
      isBestSeller: false,
      isVegan: true,
      isFeatured: false,
      texture: "suave",
      intensity: "suave",
      pairings: ["Té de rosas", "Champán"],
      accentClass: "from-cookie-400 to-cookie-600",
    },
    {
      id: "funfetti-birthday",
      name: "Funfetti Birthday Blast",
      description: "Masa de vainilla con confeti de colores y crema de buttercream. Una fiesta en cada bocado.",
      price: 6.49,
      originalPrice: null,
      image: "/images/products/slider9.png",
      category: "clásicas",
      tag: "fan favorite",
      rating: 4.7,
      reviews: 166,
      calories: 215,
      weight: "85g",
      ingredients: ["Vainilla", "Confeti", "Buttercream"],
      isNew: false,
      isBestSeller: false,
      isVegan: false,
      isFeatured: false,
      texture: "suave",
      intensity: "suave",
      pairings: ["Leche", "Limonada"],
      accentClass: "from-cookie-500 to-chocolate-500",
    },
    {
      id: "peanut-butter-crunch",
      name: "Peanut Butter Crunch",
      description: "Mantequilla de maní tostado, trozos de cacahuete y chips de chocolate oscuro.",
      price: 7.49,
      originalPrice: 8.99,
      image: "/images/products/slider10.jpg",
      category: "clásicas",
      tag: "más vendido",
      rating: 4.8,
      reviews: 241,
      calories: 280,
      weight: "95g",
      ingredients: ["Maní Tostado", "Choco Oscuro", "Miel"],
      isNew: false,
      isBestSeller: false,
      isVegan: false,
      isFeatured: false,
      texture: "crujiente",
      intensity: "medio",
      pairings: ["Leche", "Café"],
      accentClass: "from-cookie-600 to-chocolate-700",
    },
    {
      id: "salted-pretzel-caramel",
      name: "Salted Pretzel Caramel",
      description: "Trozos de pretzel salado sobre lecho de caramelo suave y masa de mantequilla.",
      price: 8.99,
      originalPrice: null,
      image: "/images/products/slider11.png",
      category: "premium",
      tag: "limitado",
      rating: 4.9,
      reviews: 78,
      calories: 255,
      weight: "90g",
      ingredients: ["Pretzel", "Caramelo", "Flor de Sal"],
      isNew: false,
      isBestSeller: false,
      isVegan: false,
      isFeatured: false,
      texture: "crujiente",
      intensity: "medio",
      pairings: ["Cerveza Artesanal", "Whisky"],
      accentClass: "from-cookie-400 to-cookie-700",
    },
    {
      id: "cinnamon-roll-swirl",
      name: "Cinnamon Roll Swirl",
      description: "Remolinos de canela y azúcar morena con glaseado de queso crema.",
      price: 7.99,
      originalPrice: 9.49,
      image: "/images/products/slider12.png",
      category: "especiales",
      tag: "nuevo",
      rating: 4.7,
      reviews: 61,
      calories: 230,
      weight: "85g",
      ingredients: ["Canela", "Azúcar Morena", "Crema de Queso"],
      isNew: true,
      isBestSeller: false,
      isVegan: false,
      isFeatured: false,
      texture: "suave",
      intensity: "suave",
      pairings: ["Té Chai", "Café con leche"],
      accentClass: "from-amber-600 to-cookie-700",
    },
    {
      id: "smores-supreme",
      name: "S'mores Supreme",
      description: "Graham cracker, malvavisco tostado y chocolate oscuro fundido.",
      price: 8.49,
      originalPrice: null,
      image: "/images/products/slider13.png",
      category: "especiales",
      tag: null,
      rating: 4.8,
      reviews: 134,
      calories: 270,
      weight: "92g",
      ingredients: ["Graham", "Malvavisco", "Choco Oscuro"],
      isNew: false,
      isBestSeller: false,
      isVegan: false,
      isFeatured: false,
      texture: "suave",
      intensity: "intenso",
      pairings: ["Chocolate Caliente", "Vino Tinto"],
      accentClass: "from-chocolate-600 to-cookie-800",
    },
    {
      id: "raspberry-white-choco",
      name: "Raspberry White Choco",
      description: "Frambuesas liofilizadas, chips de chocolate blanco belga y masa de almendra.",
      price: 9.49,
      originalPrice: 11.49,
      image: "/images/products/slider14.png",
      category: "premium",
      tag: "nuevo",
      rating: 4.6,
      reviews: 45,
      calories: 185,
      weight: "70g",
      ingredients: ["Frambuesa", "Choco Blanco", "Almendra"],
      isNew: true,
      isBestSeller: false,
      isVegan: true,
      isFeatured: false,
      texture: "crujiente",
      intensity: "suave",
      pairings: ["Prosecco", "Té frutal"],
      accentClass: "from-cookie-400 to-chocolate-500",
    },
    {
      id: "espresso-dark-roast",
      name: "Espresso Dark Roast",
      description: "Doble shot de espresso, cacao al 85% y trozos de chocolate negro.",
      price: 8.99,
      originalPrice: null,
      image: "/images/products/slider15.png",
      category: "especiales",
      tag: null,
      rating: 4.7,
      reviews: 89,
      calories: 220,
      weight: "80g",
      ingredients: ["Espresso", "Cacao 85%", "Choco Negro"],
      isNew: false,
      isBestSeller: false,
      isVegan: true,
      isFeatured: false,
      texture: "crujiente",
      intensity: "intenso",
      pairings: ["Café", "Bourbon"],
      accentClass: "from-chocolate-700 to-chocolate-900",
    },
    {
      id: "coconut-lime-zest",
      name: "Coconut Lime Zest",
      description: "Coco tostado, ralladura de lima y leche condensada. Una galleta tropical de primera.",
      price: 7.49,
      originalPrice: null,
      image: "/images/products/slider16.png",
      category: "especiales",
      tag: null,
      rating: 4.6,
      reviews: 58,
      calories: 170,
      weight: "70g",
      ingredients: ["Coco Tostado", "Lima", "Leche Condensada"],
      isNew: false,
      isBestSeller: false,
      isVegan: true,
      isFeatured: false,
      texture: "crujiente",
      intensity: "suave",
      pairings: ["Piña Colada", "Té de menta"],
      accentClass: "from-cookie-500 to-cookie-700",
    },
  ];